[package]
name = "rex"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["visualizer"]

[dependencies]
ahash = "0.8.2"
anyhow = "1.0.66"
bitflags = "1.3.2"
glam = { version = "0.22.0", features = ["mint"] }
log = "0.4.17"
mint = "0.5.9"
rand = "0.8.5"
