[package]
name = "rex"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["visualizer", "app", "app/renderer", "app/common"]

[dependencies]
anyhow = "1.0.66"
emath = { version = "0.19.0", features = ["mint"] }
log = "0.4.17"
mint = "0.5.9"
rand = "0.8.5"
